name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repozitár
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Node na runneri (Firebase CLI beží v ňom)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # 3) Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 4) Zapíš service account JSON zo secretu do súboru
      - name: Write service account key
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > ${{ github.workspace }}/serviceAccountKey.json

      # 5) (Voliteľné) vypnúť strict kontrolu engine, aby nevadilo,
      #    že functions majú "engines.node": "18", ale runner má Node 24
      - name: Relax npm engine check
        run: npm config set engine-strict false

      # 6) Nainštalovať dependencies pre Cloud Functions
      - name: Install Functions dependencies
        working-directory: functions
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # 7) Deploy functions + firestore rules cez service account
      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
        run: |
          firebase deploy --only functions,firestore:rules --project lyziarska-skola

      # 8) Inicializácia SuperAdmina (idempotentné)
      - name: Initialize SuperAdmin
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
        run: |
          node functions/initSuperAdmin.js

      # 9) Cleanup – odstráni kľúč zo súborového systému runnera
      - name: Cleanup credentials
        if: always()
        run: rm -f ${{ github.workspace }}/serviceAccountKey.json


