name: Deploy to Firebase

on:
  push:
    branches:
      - main   # alebo iná vetva, ktorú používaš

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > ${HOME}/gcloud.json
          firebase use --add lyziarska-skola
          firebase deploy --only functions,firestore:rules --token "$(firebase login:ci --no-localhost --json < ${HOME}/gcloud.json | jq -r '.refresh_token')"

